## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/api"
  to = "https://buildings-of-berlin-be.netlify.app/api"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
